### ISSUE TITLE
S**t code!

### ISSUE THREAD

**Issue by 158627746** [tarashakhurana/detecting-invisible-people#1]
I think this is something that only the author can understand, or not.Why is there no manual?and there are no comments in the your code, Reading this makes me cranky!!!!!!

**Comment by achalddave** [comment]
Thanks for your interest in our work! We encourage you to take a look at the [README](https://github.com/tarashakhurana/detecting-invisible-people/blob/main/README.md), and feel free to contact us if you have specific questions. It looks like you're new to Github; here are some examples of good issues to look at when posting your issue: [1](https://github.com/stevemao/github-issue-templates/blob/master/conversational/ISSUE_TEMPLATE.md), [2](https://github.com/TAO-Dataset/tao/issues/29), [3](https://github.com/facebookresearch/detectron2/issues/4095). That said, your current post violates the [reasonable person principle](https://www.cs.cmu.edu/~weigand/staff/), so we’re going to have to lock the issue. Feel free to open a new one!
